Param(
    [Parameter(Mandatory=$True)]
    [string]$botWebchatSecret
)

$ErrorActionPreference = "Stop"

function PostMessage($convId, $userName, $userId, $text) {
    $msg = @{
        "type"="message"
        "text"=$text
        "from" = @{
            "id"=$userId
            "name"=$userName
         }
    } | ConvertTo-Json
    Write-Host "Sending: $text"
    $res=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Method POST -Body $msg -Headers @{"Authorization" = "Bearer $botWebchatSecret"; "Content-Type" = "application/json"}
}

function performConversation ($question, $answerToAppointmentRequest, $answerToMailRequest) {
    Try {
        $conversationStart=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations" -Method POST -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json

        $userName="ScriptedUser";
        $convId=$conversationStart.conversationId;
        $myId=(New-Guid);

        PostMessage $convId $userName $myId $question

        Do {
            Write-Host "Getting messages..."
            $messages=Invoke-WebRequest -Uri "https://directline.botframework.com/v3/directline/conversations/$convId/activities" -Headers @{"Authorization" = "Bearer $botWebchatSecret"} | ConvertFrom-Json
            $question=$messages.activities | Where-Object {$_.from.id -ne $myId -and $_.text.EndsWith('?')} | Select-Object -Last 1
        } Until ($question)
            Write-Host "Received: " $question.text
        if ($question.text.Contains("appointment")) {
            PostMessage $convId $userName $myId $answerToAppointmentRequest
            }
            else {
            PostMessage $convId $userName $myId $answerToMailRequest
            }
    }
    Catch {
        Write-Host $_.Exception -ForegroundColor Red
    }
}

performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'yes' 'no'
performConversation 'What is the hotels phone number?' 'no' 'yes'
performConversation 'What is the check in time?' 'yes' 'yes'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'yes'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'yes'
performConversation 'Is there valet parking at this hotel?' 'yes' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'yes' 'no'
performConversation 'How far is the airport to the hotel?' 'yes' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'yes'
performConversation 'The valet fee is too high' 'no' 'yes'
performConversation 'What restaurants are near the hotel?' 'yes' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'yes'
performConversation 'Does this hotel have a concierge?' 'no' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'yes'
performConversation 'What is the check in time?' 'no' 'no'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'no'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'no' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'yes' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'no'
performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'yes' 'yes'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'no'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'no'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'yes'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'yes' 'no'
performConversation 'How far is the airport to the hotel?' 'yes' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'yes' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'no' 'no'
performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'yes'
performConversation 'What is the check in time?' 'yes' 'no'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'yes' 'yes'
performConversation 'Does this hotel have free breakfast?' 'yes' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'no'
performConversation 'Is there a parking fee at this hotel?' 'no' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'no' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'yes'
performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'yes'
performConversation 'What is the check in time?' 'yes' 'yes'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'yes'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'no'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'yes'
performConversation 'Is there valet parking at this hotel?' 'yes' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'no' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'yes'
performConversation 'The valet fee is too high' 'no' 'yes'
performConversation 'What restaurants are near the hotel?' 'yes' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'no'
performConversation 'Does this hotel have a concierge?' 'no' 'no'
performConversation 'Does this hotel accept pets?' 'no' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'no' 'no'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'no'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'no'
performConversation 'Is there a parking fee at this hotel?' 'no' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'no' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'no' 'no'
performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'yes' 'no'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'no'
performConversation 'Does this hotel have free breakfast?' 'no' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'no'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'no' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'yes' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'no' 'no'
performConversation 'Does this hotel have a concierge?' 'no' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'no' 'no'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'yes' 'yes'
performConversation 'Does this hotel have free breakfast?' 'yes' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'no'
performConversation 'Is there a parking fee at this hotel?' 'no' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'no'
performConversation 'How far is the airport to the hotel?' 'no' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'no'
performConversation 'Does this hotel have a concierge?' 'yes' 'yes'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'yes' 'yes'
performConversation 'What is the check in time?' 'yes' 'yes'
performConversation 'What is the check out time?' 'yes' 'no'
performConversation 'Does this hotel have a bar?' 'no' 'yes'
performConversation 'Does this hotel have free breakfast?' 'yes' 'yes' 
performConversation 'Does this hotel have a fitness center?' 'yes' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'yes'
performConversation 'Is there valet parking at this hotel?' 'yes' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'yes'
performConversation 'Directions from the airport to the hotel' 'yes' 'no'
performConversation 'How far is the airport to the hotel?' 'no' 'yes'
performConversation 'How long to drive from the airport to the hotel?' 'yes' 'yes'
performConversation 'The valet fee is too high' 'no' 'yes'
performConversation 'What restaurants are near the hotel?' 'yes' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'no'
performConversation 'Does this hotel have a concierge?' 'no' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'yes'
performConversation 'Does this hotel have a spa?' 'yes' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'no' 'no'
performConversation 'What is the check out time?' 'yes' 'yes'
performConversation 'Does this hotel have a bar?' 'no' 'yes'
performConversation 'Does this hotel have free breakfast?' 'yes' 'yes' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'no' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'yes'
performConversation 'Is there valet parking at this hotel?' 'yes' 'no'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'yes' 'yes'
performConversation 'How far is the airport to the hotel?' 'no' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'yes'
performConversation 'The valet fee is too high' 'yes' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'no' 'yes'
performConversation 'Does this hotel have a concierge?' 'yes' 'no'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'yes'
performConversation 'What is the hotels phone number?' 'no' 'yes'
performConversation 'What is the check in time?' 'yes' 'no'
performConversation 'What is the check out time?' 'yes' 'no'
performConversation 'Does this hotel have a bar?' 'yes' 'no'
performConversation 'Does this hotel have free breakfast?' 'yes' 'no' 
performConversation 'Does this hotel have a fitness center?' 'yes' 'yes'
performConversation 'Does this hotel have a romance package?' 'yes' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'no' 'yes'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'no'
performConversation 'The parking fee is too much' 'no' 'no'
performConversation 'Directions from the airport to the hotel' 'no' 'yes'
performConversation 'How far is the airport to the hotel?' 'yes' 'no'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'no'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'no' 'no'
performConversation 'Does this hotel have a concierge?' 'no' 'yes'
performConversation 'Does this hotel accept pets?' 'yes' 'no'
performConversation 'Does this hotel have a spa?' 'no' 'no'
performConversation 'What is the hotels phone number?' 'no' 'no'
performConversation 'What is the check in time?' 'no' 'yes'
performConversation 'What is the check out time?' 'no' 'no'
performConversation 'Does this hotel have a bar?' 'yes' 'yes'
performConversation 'Does this hotel have free breakfast?' 'yes' 'no' 
performConversation 'Does this hotel have a fitness center?' 'no' 'yes'
performConversation 'Does this hotel have a romance package?' 'yes' 'no'
performConversation 'Where do I park at this hotel?' 'no' 'no'
performConversation 'Is there valet parking at this hotel?' 'yes' 'no'
performConversation 'Is there a parking fee at this hotel?' 'yes' 'yes'
performConversation 'The parking fee is too much' 'yes' 'no'
performConversation 'Directions from the airport to the hotel' 'yes' 'yes'
performConversation 'How far is the airport to the hotel?' 'yes' 'yes'
performConversation 'How long to drive from the airport to the hotel?' 'no' 'no'
performConversation 'The valet fee is too high' 'no' 'yes'
performConversation 'What restaurants are near the hotel?' 'no' 'no'
performConversation 'What can my family do near the hotel?' 'yes' 'yes'